Service:
  NodePort: 32200
  Port: 3128
  ExternalVisibility: NodePort
  MonitoringPort: 3401
Alarm:
  Site: "MWT2"
  AaasServer: aaas.atlas-ml.org
NodeSelection:
  OpenDefaultMonPort: True
  Hostname: sl-uc-xcache1.slateci.io
SquidConf:
  Logfile_Rotate: !<!> 20
  CleanLog: False
  IPRange: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 72.36.96.0/24 149.165.224.0/23 192.170.240.0/23
  LogToStdout: False
  RequestEphemeralSize: 1024
  MaxAccessLog: !<!> 5000M
  CacheSize: 25000
  MaximumObjectSizeInMemory: !<!> 1048704
  DisableDiskCache: False
  CacheDirOnHost: "/nvme/squid"
  DisableLogging: True
  UseHostpathLogDir: True
  CPU: 4
  CacheMem: "32768"
  LimitEphemeralSize: 2048
  MonitoringIPRange: 127.0.0.1/32 192.170.227.128/32 128.135.158.191/32 188.185.0.0/17 131.225.240.232/32 128.142.0.0/16 188.184.128.0/17 188.185.48.0/20 188.185.128.0/17
Instance: "prod"
ImageTag: 3.6-testing
