Instance: "net2-1"

NodeSelection:
  OpenDefaultMonPort: True
  Hostname: atlas-slate01

Service:
  Port: 3128
  MonitoringPort: 3401
  NodePort: 32200
  ExternalVisibility: NodePort

ImageTag: 3.6-testing

SquidConf:
  CPU: 4
  CacheMem: "32768"
  CacheSize: "25000"
  CacheDirOnHost: True
  DisableDiskCache: False
  MaximumObjectSizeInMemory: "1048704"
  IPRange: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 192.5.207.199/32 192.170.227.128/32
  MonitoringIPRange: 127.0.0.1/32 192.170.227.128/32 128.135.158.191/32 188.185.0.0/17 131.225.240.232/32 128.142.0.0/16 188.184.128.0/17 188.185.48.0/20 188.185.128.0/17
  RequestEphemeralSize: 1024
  LimitEphemeralSize: 2048
  CleanLog: False
  LogToStdout: False
  UseHostpathLogDir: False
  Logfile_Rotate: "5"
  MaxAccessLog: "5000M"

Alarm:
  Site: "NET2"
  AaasServer: aaas.atlas-ml.org
